### ISSUE TITLE
Code example is outdated

### ISSUE THREAD

**Issue by johnnyunar** [filias/gpwebpay#62]
Hi! 

Is this project still active? I am trying to use your API wrapper, but there is a lot of outdated code in the example. For example `key_bytes` parameter is now just `key`. 
`gw.is_callback_valid(response.url, key_bytes=key_bytes)` 
now looks like this in the package:
`gw._is_callback_valid(response.url, digest=digest, digest1=digest1, key=key_bytes)`

What is supposed to be passed to the function using the digest parameters? I am a bit confused now.

Thank you for your response!
Johnny

**Comment by filias** [comment]
Hi @johnunar 

thank you for the message. Yes, you are right, the readme is outdated. I haven't been having enought ime for this, sorry. I will try to update it this week.

You should use `get_payment_result` instead of `is_callback_valid`. https://github.com/filias/gpwebpay/blob/1f5e9fffa18dffdbdf79da3b25a1189a61b6b4ea/gpwebpay/gpwebpay.py#L118

There is an example in the tests which uses my GPWEBPAY test keys (you should substitute those for your values).
https://github.com/filias/gpwebpay/blob/1f5e9fffa18dffdbdf79da3b25a1189a61b6b4ea/tests/test_gpwebpay.py#L79
I thought of removing that from the tests but then I thought it could be useful for someone to see what goes where.

I am happy to help you if you have any troubles just my time is a bit limited atm :)

I hope this helps.

**Comment by johnnyunar** [comment]
Ok, great:) Thank you very much. 

I would also appreciate if we were able to change the environment variable source. Right now the config file reads variables from the .env file. But there are multiple cases where it is desirable to use global variables using `os.environ.get()`. 

Keep up the great work!:)

**Comment by filias** [comment]
Yeah, I am actually considering using pydantic's BaseSettings class for the envs. Let's see if I manage this soon :)
Thanks for the suggestion :)

**Comment by filias** [comment]
Hi @johnunar I have updated the readme, I hope it is more clear now.

Thanks again for reporting it. Have a nice day!
